### ISSUE TITLE
No performance gain

### ISSUE THREAD

**Issue by bkzshabbaz** [Xilinx/SDSoC_Examples#1]
I built the ```parallel_accel``` example for my zedboard and noticed it did not produce any performance gain over the software implementation:
```
root@avnet-digilent-zedboard-2017_2:/mnt# ./run.elf 
Number of average CPU cycles running application in software: 38843
Number of average CPU cycles running application sequentially in hardware: 75610
Number of average CPU cycles running application parallel in hardware: 54383
Parallel speed up compare to sequential execution is: 1.39032
Note: Speed up is meaningful for real hardware execution only, not for emulatio.
TEST PASSED
```

Why is this the case?

**Comment by heeran-xilinx** [comment]
hi @bkzshabbaz , 
Intention of this example is not to show improvement with respect to CPU cycles. Main focus of this example is to show improvement what user can achieve using async_wait and can do parallel computation. Here it shows 1.39x improvement using async_wait with respect to sequential steps.  

Why it does not show improvement with respect CPU, as it could be functionality could be simple enough to run on CPU instead of migrating to hw. We if you try any valid application, which is time consuming on CPU, you may see some improvement with respect to cpu cycles.
For example, shift_register:
https://github.com/Xilinx/SDSoC_Examples/tree/master/cpp/getting_started/shift_register

Shows 4x improvement as below:
Number of CPU cycles running application in software: 41908
Number of CPU cycles running application in hardware: 8878
Speed up: 4.72043

Does it clarify your doubt?

-Heera

**Comment by bkzshabbaz** [comment]
Fair enough, but why is the performance improvement of the async pragma at 1.4?  I would have expected it closer to 2x.  How can I gain a better perspective?

**Comment by heeran-xilinx** [comment]
hi @bkzshabbaz ,
We would like to correct our previous statement that actually SDSoC does auto infer the dataflow between two hw function call. So ideally following two call should give you same performance if we can for multiple iteration:
case 1)
for(i = 0 i < 1024 ; i++) { 
seq_hw_ctr.start();   //   Launch Hardware Solution    
vadd_accel(source_in1,   source_in2,    source_vadd_hw_results,   size);   
vmul_accel(source_in1,   source_in2,    source_vmul_hw_results,   size);   
seq_hw_ctr.stop();
}
case 2)
for (i = 0 ; i < 1024; i++) {
par_hw_ctr.start();   //   Launch Hardware Solution   
#pragma   SDS async(1)   
vadd_accel(source_in1,   source_in2,    source_vadd_hw_results,   size);   
#pragma   SDS async(2)   
vmul_accel(source_in1,   source_in2,    source_vmul_hw_results,   size);   
#pragma   SDS wait(1)   
#pragma   SDS wait(2)   
par_hw_ctr.stop();
}

Number of average CPU cycles running application sequentially in hardware: 85907
Number of average CPU cycles running application parallel in hardware: 80969
Parallel speed up compare to sequential execution is: 1.06099

so using async_wait, we are getting same results what we are can get using SDSoC auto inference of dataflow. 
(Refer to pg19 in optimization guide: https://www.xilinx.com/support/documentation/sw_manuals/xilinx2017_4/ug1235-sdsoc-optimization-guide.pdf#nameddest=xImprovingSystemPerformance)

To see the 2x improvement, we explicitly added wait statements between two functions call to run them sequentially:
case 3)
for(i=0; i < 1024; i++){
seq_hw_ctr.start();   //   Launch Hardware Solution   
#pragma   SDS async(1)  
vadd_accel(source_in1,   source_in2,     source_vadd_hw_results,   size);   
#pragma   SDS wait(1)   ]
#pragma   SDS async(2)   
vmul_accel(source_in1,   source_in2,    source_vmul_hw_results,   size);   
#pragma   SDS wait(2)   
par_hw_ctr.stop();

Using above logic, we can notice 2x improvement.

-Heera
